name: warehouse

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: warehouse
    depends_on:
      - postgres
    env_file:
      - ../.env
    ports:
      - "8081:8080"

  postgres:
    image: postgres:17
    container_name: db-warehouse
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "54433:5432"
    volumes:
      - warehouse_postgres_data:/var/lib/postgresql/data

volumes:
  warehouse_postgres_data: